library(tidyverse)
library(readxl)
library(scales)

setwd("~/Dropbox/grad/research/")

g3Depth <- read_csv("g3Depth/g3Depth_speciesWithTrophicPredictions_fall2023_27.csv")

g3Depth <- g3Depth %>% distinct(tax_name)

colnames(g3Depth) <- "taxa"

g <- g3Depth %>% mutate(gradients = "G3")

g <- g %>% distinct(taxa, gradients) %>% arrange(taxa) 

asv <- read_excel("asvAnalysis/elaina_g123_18s_master 2.xlsx")

asv <- asv %>% mutate(species = ifelse(str_detect(species, "_sp.$"), "NA", species))

asv %>% filter(str_detect(species, "sp$")) %>% distinct(species)

asv <- asv %>% mutate(species = ifelse(str_detect(species, "_sp$"), "NA", species))

asv <- asv %>% mutate(species = ifelse(species == "NA", genus, species))

asv <- asv %>% filter(species != "NA")

asv <- asv %>% mutate(genus = str_replace(species, "_[a-zA-Z0-9_\\.]{1,}", ""))

asv <- asv %>% mutate(genus = ifelse(str_detect(genus, "MAST-4"), "Stramenopiles", genus))

asv <- asv %>% mutate(species = ifelse(str_detect(species, "MAST-4"), "Stramenopiles_MAST-4", species))

asv <- asv %>% mutate(species = ifelse(species == "Gephyrocapsa_oceanica", "Emiliania_huxleyi", species))
asv <- asv %>% mutate(genus = ifelse(genus == "Gephyrocapsa", "Emiliania", genus))

distinctSpecies <- asv %>% distinct(genus, species) %>% arrange(genus, species)

g <- g %>% mutate(genus = str_replace(taxa, " [a-zA-Z0-9_\\.\\- ]{1,}", ""))

g <- g %>% mutate(genus = str_replace(genus, "\\'lucimarinus\\'", ""))

#https://roscoff-culture-collection.org/pelagomonadaceaecladecsp
g <- g %>% mutate(genus = ifelse(taxa == "Pelagophyceae sp. RCC1024", "Pelagomonadaceae", genus))
g <- g %>% mutate(taxa = ifelse(taxa == "Pelagophyceae sp. RCC1024", "Pelagomonadaceae_clade_C_sp.", taxa))

g <- g %>% mutate(taxa = ifelse(taxa == "Ostreococcus sp. RCC809", "Ostreococcus_clade_B", taxa))

g %>% anti_join(distinctSpecies, by = c("genus"))

asv <- asv %>% select(sampleID, cruise, filter, latitude, longitude, depth, featureID, genus:counts)

g <- g %>% mutate(species = str_replace(taxa, " ", "_"))

g %>% anti_join(asv, by = c("species"))

#https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1333877
g <- g %>% mutate(species = ifelse(taxa == "Brandtodinium nutricula", "Zooxanthella_nutricula", species))
g <- g %>% mutate(genus= ifelse(taxa == "Brandtodinium nutricula", "Zooxanthella", genus))

g <- g %>% mutate(species = ifelse(species == "Ostreococcus_sp. 'lucimarinus'", "Ostreococcus_lucimarinus", species))

g <- g %>% mutate(species = ifelse(species == "Phaeocystis_sp. RCC851", "Phaeocystis_globosa", species))

g <- g %>% mutate(species = ifelse(species == "Prasinoderma_singulare", "Prasinoderma_singularis", species))

g <- g %>% mutate(species = ifelse(taxa == "Stramenopiles sp. TOSAG23-2", "Stramenopiles_MAST-4", species))
g <- g %>% mutate(species = ifelse(taxa == "Stramenopiles sp. TOSAG23-3", "Stramenopiles_MAST-4", species))

asv_1 <- asv %>% semi_join(g, by = c("species"))

miss <- g %>% anti_join(asv, by = c("species"))

asv_2 <- asv %>% semi_join(miss, by = c("genus")) %>% 
  semi_join(g, by = c("species" = "genus"))

asv <- bind_rows(asv_1 %>% mutate(level = "species"), asv_2 %>% mutate(level = "genus"))

asv %>% distinct(species) %>% nrow()
g %>% distinct(species) %>% nrow()

asv <- asv %>% mutate(oldSpecies = ifelse(species == "Ostreococcus_lucimarinus", "Ostreococcus sp. 'lucimarinus'", species))
asv <- asv %>% mutate(oldSpecies = ifelse(species == "Pelagomonadaceae_clade_C_sp.", "Pelagophyceae sp. RCC1024", oldSpecies))
asv <- asv %>% mutate(oldSpecies = ifelse(species == "Zooxanthella_nutricula", "Brandtodinium nutricula", oldSpecies))
asv <- asv %>% mutate(oldSpecies = ifelse(species == "Prasinoderma_singularis", "Prasinoderma_singulare", oldSpecies))

asv <- asv %>% mutate(oldSpecies = str_replace(oldSpecies, "_", " "))

asv %>% distinct(cruise, depth) %>% arrange(cruise, depth)

asv %>% filter(is.na(depth))

asv <- asv %>% arrange(species, featureID) 

distinctASV <- asv %>% distinct(species, featureID)

distinctASV <- distinctASV %>% mutate(asvNum = ifelse(species != lag(species), 1, NA))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID == "022891d41c76e21fa0e755e5fe758dad", 1, asvNum))

distinctASV %>% filter(featureID != lag(featureID) & species == lag(species))

distinctASV %>% group_by(species) %>% summarize(n = n()) %>% arrange(desc(n))

distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(featureID != lag(featureID) & species == lag(species), lag(asvNum)+1, asvNum))

distinctASV %>% filter(is.na(asvNum)) %>% nrow()
distinctASV %>% filter(is.na(asvNum)) %>% distinct(species)
distinctASV <- distinctASV %>% mutate(asvNum = ifelse(species == "Aureococcus_anophagefferens", 1:87, asvNum))
distinctASV %>% filter(is.na(asvNum))

distinctASV$asvNum <- as.character(distinctASV$asvNum)

g3Depth <- asv %>% filter(cruise == "G3")

nrow(g3Depth)
g3Depth <- g3Depth %>% left_join(distinctASV, by = c("species", "featureID"))
nrow(g3Depth)

g3Depth %>% distinct(depth) %>% arrange(depth)

g3Depth %>% distinct(oldSpecies) %>% filter(str_detect(oldSpecies, " "))

mixed <- read_csv("g1G2G3/mixedSpeciesStrict_dielIncubations.csv")

g3Depth %>% semi_join(mixed, by = c("oldSpecies" = "taxa")) %>% filter(level == "species") %>% distinct(oldSpecies) 
g3Depth %>% anti_join(mixed, by = c("oldSpecies" = "taxa")) %>% filter(level == "species") %>%  distinct(oldSpecies)

g3Depth %>% mutate(latitude = round(latitude)) %>%
  mutate(depth = ifelse(depth <= 15, "Surface", depth)) %>% distinct(depth)

g3Depth %>% mutate(latitude = round(latitude)) %>%
  mutate(depth = ifelse(depth <= 15, "Surface", depth)) %>%
  mutate(depth = factor(depth, levels = c("Surface", "45", "60", "75", "90", "100", "125"))) %>%
  filter(oldSpecies == "Karlodinium veneficum") %>%
  group_by(latitude, oldSpecies, featureID, asvNum, depth) %>%
  summarize(sd = sd(counts), counts = sum(counts), n = n()) %>%
  ggplot(aes(x = latitude, y = counts, fill = asvNum)) +
  geom_bar(stat = 'identity', width = .75, color = 'black') +
  geom_vline(aes(xintercept=32.45), colour="red", linetype="dashed") + 
  geom_vline(aes(xintercept=35), colour="black", linetype="dashed") + 
  theme_classic() +
  theme_bw() +
  theme(strip.background =element_rect(fill="white")) +
  theme(strip.text.x = element_text(size = 26, color = 'black')) + 
  theme(strip.text.y = element_text(size = 18, color = 'black')) + 
  theme(axis.text.x = element_text(size = 22, color = 'black'))  + 
  theme(axis.text.y = element_text(size = 18, color = 'black')) + 
  theme(axis.title.y = element_text(size = 26, color = 'black')) + 
  theme(legend.text = element_text(size = 20, color = 'black')) +
  theme(legend.title = element_text(size = 22, color = 'black')) +
  theme(axis.title.x = element_text(size = 26, color = 'black')) + 
  labs(color = "Taxa", y = "Relative abundance", x = "Latitude (°N)") +
  facet_grid(rows = vars(depth), cols = vars(oldSpecies), scales = "free_y") + 
  theme(legend.position = 'none') + 
  scale_x_continuous(breaks = c(20,25,30,35,40)) +  
  scale_y_continuous(breaks=pretty_breaks(n = 2))

ggsave("asvAnalysis/speciesWithTrophicModePredictions_ASVAbundanceOverG3_depth_noOutliers_karlodiniumVeneficum.png", height = 10, width = 6.1)
ggsave("asvAnalysis/speciesWithTrophicModePredictions_ASVAbundanceOverG3_depth_noOutliers_karlodiniumVeneficum.svg", height = 10, width = 6.1)
